#!/bin/bash

set -eux

FLY_TARGET="${1:-}"
DATADOG_API_KEY="${2:-}"
PIPELINE_NAME="monitoring"

function usage() {
  echo "usage: $0 <fly-target>" >&2
  exit 1
}

[ -n "$FLY_TARGET" ] || usage
[ -n "$DATADOG_API_KEY" ] || usage

fly -t "$FLY_TARGET" set-pipeline -n -p "$PIPELINE_NAME" -c pipeline.yml
fly -t "$FLY_TARGET" unpause-pipeline -p "$PIPELINE_NAME"
fly -t "$FLY_TARGET" expose-pipeline -p "$PIPELINE_NAME"

erb monitor.yml

fly -t "$FLY_TARGET" set-pipeline -n -p "$PIPELINE_NAME"-stats -c <(erb monitor.yml) \
  -v atc_url="$(fly targets | grep "$FLY_TARGET" | head -n 1 | awk '{print $2}')" \
  -v datadog_api_key="$DATADOG_API_KEY" \
  -v interval=30s \
  -v pipeline_name="$PIPELINE_NAME" \
  -v team_name=main
fly -t "$FLY_TARGET" unpause-pipeline -p "$PIPELINE_NAME"-stats
