#!/bin/bash

set -eux

DATADOG_API_KEY="${1:-}"
USERNAME="${2:-}"
PASSWORD="${3:-}"
PIPELINE_NAME="monitoring"

function usage() {
  echo "usage: $0 <datadog_api_key> <username> <password>" >&2
  exit 1
}

[ -n "$DATADOG_API_KEY" ] || usage
[ -n "$USERNAME" ] || usage
[ -n "$PASSWORD" ] || usage

fly -t wings-monitoring set-pipeline -n -p "$PIPELINE_NAME" -c pipeline.yml
fly -t wings-monitoring unpause-pipeline -p "$PIPELINE_NAME"
fly -t wings-monitoring expose-pipeline -p "$PIPELINE_NAME"

fly -t ci set-pipeline -n -p "$PIPELINE_NAME"-stats -c <(erb monitor.yml) \
  -v atc_url="$(fly targets | grep "wings-monitoring" | head -n 1 | awk '{print $2}')" \
  -v datadog_api_key="$DATADOG_API_KEY" \
  -v interval=30s \
  -v password="$PASSWORD" \
  -v pipeline_name="$PIPELINE_NAME" \
  -v team_name=monitoring \
  -v username="$USERNAME"
fly -t ci unpause-pipeline -p "$PIPELINE_NAME"-stats
